apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    costcenter: amer
    location: NA
    type: frontent
spec:
  containers:
    - name: nginx-container
      image: nginx