apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeName: wordpress-persistent-storage